name: Test & Release
on:
  push:
    branches:
      - released
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
  GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
jobs:
  test-and-release:
    name: Test & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm i

      - name: Release
        run: npm run release
